version: '3.5'

services:
  localstack:
    image: localstack/localstack:0.8.6
    ports:
      - "4572:4572"
      - "4583:4583"
    environment:
      - SERVICES=s3,ssm
      - DEFAULT_REGION=us-east-1
    networks:
      - nextflow
  postgres:
    hostname: postgres
    image: pennsieve/pennsievedb:latest-seed
    expose:
      - "5432"
    networks:
      - nextflow
    volumes:
      - ./tests:/tests/
    healthcheck:
      test: pg_isready -U postgres
      interval: 15s
      timeout: 10s
      retries: 10
  redis:
    hostname: redis
    image: pennsieve/redis:latest
    expose:
      - "6379"
    networks:
      - nextflow
networks:
  nextflow:
    name: ${NETWORK_NAME}
